spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_study?characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.mystudy.mock
  mapper-locations: mybatis/mapper/**/*.xml